swagger: "2.0"
info:
  title: Fusion Harbor Microservices API
  description: API for Fusion Harbor Microservices
  version: 1.0.0
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /login:
    post:
      summary: Authenticate a user
      operationId: loginUser
      tags:
        - auth
      parameters:
        - name: loginRequest
          in: body
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        200:
          description: Successfully logged in
          schema:
            $ref: "#/definitions/LoginResponse"
        400:
          description: Bad request
        500:
          description: Internal server error

  /users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - auth
      parameters:
        - name: createUserRequest
          in: body
          schema:
            $ref: "#/definitions/CreateUserRequest"
      responses:
        200:
          description: Successfully created user
          schema:
            $ref: "#/definitions/CreateUserResponse"
        400:
          description: Bad request
        500:
          description: Internal server error

    get:
      summary: Get users
      operationId: getUsers
      tags:
        - auth
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        200:
          description: Successfully retrieved users
          schema:
            $ref: "#/definitions/GetUsersResponse"
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /users/{id}:
    get:
      summary: Get user information
      operationId: getUser
      tags:
        - auth
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        200:
          description: Successfully retrieved user information
          schema:
            $ref: "#/definitions/GetUserResponse"
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /project:
    post:
      summary: Create a new project
      operationId: createProject
      tags:
        - project
      parameters:
        - name: createProjectRequest
          in: body
          schema:
            $ref: "#/definitions/CreateProjectRequest"
      responses:
        200:
          description: Successfully created project
          schema:
            $ref: "#/definitions/CreateProjectResponse"
        400:
          description: Bad request
        500:
          description: Internal server error

  /project/{id}:
    get:
      summary: Get project information
      operationId: getProject
      tags:
        - project
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully retrieved project information
          schema:
            $ref: "#/definitions/GetProjectResponse"
        400:
          description: Bad request
        500:
          description: Internal server error

definitions:
  LoginRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  CreateUserRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      email:
        type: string
      role:
        type: string

  CreateUserResponse:
    type: object
    properties:
      id:
        type: string

  GetUserResponse:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      email:
        type: string
      role:
        type: string

  GetUsersResponse:
    type: object
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/GetUserResponse"

  CreateProjectRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string

  CreateProjectResponse:
    type: object
    properties:
      id:
        type: string

  GetProjectResponse:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
