// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/project/project.proto

package project

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5832a92e4472a12b, []int{0}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProjectResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectResponse) Reset()         { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()    {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5832a92e4472a12b, []int{1}
}

func (m *GetProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectResponse.Unmarshal(m, b)
}
func (m *GetProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectResponse.Merge(m, src)
}
func (m *GetProjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectResponse.Size(m)
}
func (m *GetProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectResponse proto.InternalMessageInfo

func (m *GetProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProjectResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProjectResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5832a92e4472a12b, []int{2}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateProjectResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5832a92e4472a12b, []int{3}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateProjectResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProjectRequest)(nil), "project.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "project.GetProjectResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "project.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "project.CreateProjectResponse")
}

func init() { proto.RegisterFile("api/project/project.proto", fileDescriptor_5832a92e4472a12b) }

var fileDescriptor_5832a92e4472a12b = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0x15, 0x17, 0x47, 0x5c, 0x30, 0x28, 0xd4, 0x8a, 0xb2, 0xd4, 0x8b, 0xa7, 0x16,
	0xdd, 0x27, 0x50, 0x11, 0x2f, 0x22, 0xb2, 0xde, 0xf6, 0x96, 0xa6, 0xe3, 0x6e, 0x84, 0x76, 0x62,
	0x26, 0xf5, 0x95, 0x7c, 0x4d, 0xa1, 0x6d, 0xb4, 0xdb, 0xdd, 0x9e, 0x92, 0x99, 0xf9, 0xf3, 0xf3,
	0xe5, 0x67, 0xe0, 0x5c, 0x1a, 0x9d, 0x19, 0x4b, 0x9f, 0xa8, 0x9c, 0x3f, 0x53, 0x63, 0xc9, 0x91,
	0x98, 0x74, 0x65, 0x72, 0x0d, 0x27, 0xcf, 0xe8, 0xde, 0xda, 0x6a, 0x81, 0x5f, 0x35, 0xb2, 0x13,
	0x53, 0x08, 0x75, 0x11, 0x05, 0xb3, 0xe0, 0xe6, 0x70, 0x11, 0xea, 0x22, 0x59, 0x82, 0xe8, 0x8b,
	0xd8, 0x50, 0xc5, 0x38, 0x54, 0x09, 0x01, 0xfb, 0x95, 0x2c, 0x31, 0x0a, 0x9b, 0x4e, 0x73, 0x17,
	0x33, 0x38, 0x2a, 0x90, 0x95, 0xd5, 0xc6, 0x69, 0xaa, 0xa2, 0xbd, 0x66, 0xd4, 0x6f, 0x25, 0x2f,
	0x70, 0xfa, 0x68, 0x51, 0x3a, 0x1c, 0x30, 0x78, 0xb7, 0x60, 0xdc, 0x2d, 0xdc, 0x76, 0xbb, 0x87,
	0xb3, 0x81, 0xdb, 0x08, 0x6c, 0x04, 0x93, 0x12, 0x99, 0xe5, 0xca, 0xf3, 0xfa, 0xf2, 0xee, 0x27,
	0x80, 0x69, 0xf7, 0xfa, 0x1d, 0xed, 0xb7, 0x56, 0x28, 0x9e, 0x00, 0xfe, 0xff, 0x2f, 0xe2, 0xd4,
	0x67, 0xb9, 0x95, 0x5c, 0x7c, 0xb1, 0x73, 0xd6, 0x31, 0xbc, 0xc2, 0xf1, 0x06, 0x9c, 0xb8, 0xfc,
	0x53, 0xef, 0x8a, 0x20, 0xbe, 0x1a, 0x1b, 0xb7, 0x7e, 0x0f, 0xf3, 0xe5, 0xed, 0x4a, 0xbb, 0x75,
	0x9d, 0xa7, 0x8a, 0xca, 0xec, 0xa3, 0x66, 0x4d, 0xd5, 0x5a, 0xda, 0x9c, 0x6c, 0x56, 0x6a, 0x65,
	0x89, 0x5b, 0x7c, 0xce, 0x7a, 0x7b, 0x90, 0x1f, 0x34, 0x0b, 0x30, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xcb, 0xc9, 0xb8, 0xdd, 0x1d, 0x02, 0x00, 0x00,
}
